version: '2'
services:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./app:/usr/share/nginx/html
  networks:
    - docker-network
networks:
  docker-network:
    driver: bridge
